import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";
import Footer from "./Components/Footer/Footer";


export const metadata: Metadata = {
  title: "Always Apply",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="">
        <Navbar />
        {children}
        <Footer/>
        </main>
      </body>
    </html>
  );
}
